# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  # format markdown files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        types: [markdown]
        args: ["--prose-wrap", "always", "--print-width", "100"]

  # Misc checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  # Linting on Dockerfile
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
    hooks:
      - id: hadolint
