name: build-and-push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-image-tag:
          - 3.10-slim-bullseye
        mlflow-version:
          - 1.25.1
        include:
          - mlflow-version: 1.25.1
            python-image-tag: 3.10-slim-bullseye
            latest: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./mlflow/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlflow:${{ matrix.mlflow-version }}-${{ matrix.python-image-tag }}
            ${{ matrix.latest && ${{ secrets.DOCKER_HUB_USERNAME }}/mlflow:latest || }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mlflow:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mlflow:buildcache,mode=max
